name: Main
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  FULL_PACKAGE_VERSION: ${{ format('0.1.{0}+{1}', github.run_number, github.sha) }}
  PACKAGE_VERSION: ${{ format('0.1.{0}', github.run_number) }}

jobs:
  sonar:
    name: Sonar Analysis
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
  
  tests:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        shell: bash
        run: |
          dotnet build  ${{ github.workspace }}/HttpClientInjector.sln \
          dotnet test ${{ github.workspace }}/test/HttpClientInjector.Tests.csproj
  
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          dotnet publish \
            ${{ github.workspace }}/src/HttpClientInjector.csproj \
            -c Release \
            -p:Version=${FULL_PACKAGE_VERSION} \
            -o ./output
      - name: Upload Package
        uses: actions/upload-artifact@v2.2.4
        with:
          name: package
          path: ./output
          retention-days: 0

  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: package
        path: ./output
    - name: Upload to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        PACKAGE_NAME: ${{ format('HttpClientInjector.{0}.nupkg', env.PACKAGE_VERSION) }}
      run: |
        dotnet nuget push ./output/${PACKAGE_NAME} \
          -k ${NUGET_API_KEY} \
          -s https://api.nuget.org/v3/index.json
